# Listado de  tareas pertenecientes a un proyecto
GET http://localhost:4000/api/projects/672c48d7b8ef29d3b148b1af/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjdkZTcwZjNkYmNhYmQ4YzZjMDVmNSIsImlhdCI6MTczMDgzMDA1MiwiZXhwIjoxNzMyMTI2MDUyfQ._KvmkvtSFQK0dRp8pzKqQJzxMvlf2i7KK_iYP87xp54

###

# Listado de Tarea Especifica
GET http://localhost:4000/api/projects/672c48d7b8ef29d3b148b1af/tasks/672fd48006ffe4d3a2b723b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjdkZTcwZjNkYmNhYmQ4YzZjMDVmNSIsImlhdCI6MTczMDgzMDA1MiwiZXhwIjoxNzMyMTI2MDUyfQ._KvmkvtSFQK0dRp8pzKqQJzxMvlf2i7KK_iYP87xp54
###

#Validacion envio de campos vacios
POST http://localhost:4000/api/projects/672a7a273fff4fae4bb53bc3/tasks
Content-Type: application/json
Accept-Language:en-US,en;q=0.5

{
  "name": "",
  "description": "Buscar el mejor framework de css para este proyecto"
}


###

# Crear un Tarea *METODO POST*
POST http://localhost:4000/api/projects/672be573ffea8d55f59a5a70/tasks
Content-Type: application/json
Accept-Language:en-US,en;q=0.5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjdkZTcwZjNkYmNhYmQ4YzZjMDVmNSIsImlhdCI6MTczMDgzMDA1MiwiZXhwIjoxNzMyMTI2MDUyfQ._KvmkvtSFQK0dRp8pzKqQJzxMvlf2i7KK_iYP87xp54

{
    "name": "Definir framework para backend 3",
    "description": "Buscar framework del lado del servidor con BD Postgress 3"
}

###

# Actulizar una TArea *METODO PUT*
PUT http://localhost:4000/api/projects/671931db6cd1c21ab8a97769/tasks/671933eb6cd1c21ab8a97776
Content-Type: application/json
Accept-Language:en-US,en;q=0.5

{
  "name": "tarea actualizada",
  "description": "Descripcion actualizada"
}

###

# Actulizar un Project *METODO POST*
POST http://localhost:4000/api/projects/671931db6cd1c21ab8a97769/tasks/671933eb6cd1c21ab8a97776/status
Content-Type: application/json
Accept-Language:en-US,en;q=0.5

{
    "status":"inProgress"
  }

###

# Eliminar Project *METODO DELETE*
DELETE http://localhost:4000/api/projects/672be573ffea8d55f59a5a70/tasks/672fa95aa137c84d4ec02863
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjdkZTcwZjNkYmNhYmQ4YzZjMDVmNSIsImlhdCI6MTczMDgzMDA1MiwiZXhwIjoxNzMyMTI2MDUyfQ._KvmkvtSFQK0dRp8pzKqQJzxMvlf2i7KK_iYP87xp54

###
